"""Bid generation service using LLM."""

import json
import uuid

from openai import AsyncOpenAI
from pydantic import BaseModel, Field
from tenacity import retry, stop_after_attempt, wait_exponential

from app.core.config import get_settings
from app.core.logging import get_logger
from app.models.responses import LineItem
from app.prompts.templates import BID_GENERATION_PROMPT, BID_GENERATION_SYSTEM_PROMPT

logger = get_logger(__name__)


class BidPackage(BaseModel):
    """Bid package generated by LLM."""

    bid_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    scope_of_work: str = Field(...)
    line_items: list[LineItem] = Field(default_factory=list)
    labor_cost: float = Field(...)
    material_cost: float = Field(...)
    subtotal: float = Field(...)
    markup_amount: float = Field(...)
    total_price: float = Field(...)
    exclusions: list[str] = Field(default_factory=list)
    inclusions: list[str] = Field(default_factory=list)
    schedule: dict = Field(default_factory=dict)
    payment_terms: str = Field(...)
    warranty_terms: str = Field(...)
    closing_statement: str = Field(...)


class BidService:
    """Service for generating professional bid packages using LLM."""

    def __init__(self):
        """Initialize bid service."""
        self.settings = get_settings()
        self._client = None

    def _get_client(self) -> AsyncOpenAI:
        """Get or create OpenAI client."""
        if self._client is None:
            if not self.settings.openai_api_key:
                logger.warning("no_openai_api_key_mock_mode_active")
            self._client = AsyncOpenAI(api_key=self.settings.openai_api_key or "mock-key")
        return self._client

    def _create_json_schema(self) -> dict:
        """Create JSON schema for structured output."""
        return {
            "scope_of_work": "string",
            "line_items": [
                {
                    "description": "string",
                    "quantity": "number",
                    "unit": "string",
                    "unit_cost": "number",
                    "total": "number",
                }
            ],
            "labor_cost": "number",
            "material_cost": "number",
            "subtotal": "number",
            "markup_amount": "number",
            "total_price": "number",
            "exclusions": ["string"],
            "inclusions": ["string"],
            "schedule": {
                "phase_1": "string",
                "phase_2": "string",
            },
            "payment_terms": "string",
            "warranty_terms": "string",
            "closing_statement": "string",
        }

    def _prepare_takeoff_summary(self, takeoff_data: dict) -> str:
        """Format takeoff data for prompt."""
        summary_parts = []

        if "rooms" in takeoff_data:
            summary_parts.append("Rooms:")
            for room in takeoff_data["rooms"]:
                summary_parts.append(
                    f"  - {room.get('name', 'Unknown')}: {room.get('dimensions', 'N/A')} "
                    f"({room.get('area', 0)} sq ft)"
                )

        if "openings" in takeoff_data:
            summary_parts.append("\nOpenings:")
            for opening in takeoff_data["openings"]:
                summary_parts.append(
                    f"  - {opening.get('opening_type', 'Unknown')}: "
                    f"{opening.get('count', 0)} units @ {opening.get('size', 'N/A')}"
                )

        if "fixtures" in takeoff_data:
            summary_parts.append("\nFixtures:")
            for fixture in takeoff_data["fixtures"]:
                summary_parts.append(
                    f"  - {fixture.get('fixture_type', 'Unknown')} "
                    f"({fixture.get('category', 'N/A')}): {fixture.get('count', 0)} units"
                )

        if "materials" in takeoff_data:
            summary_parts.append("\nMaterials:")
            for material in takeoff_data["materials"]:
                summary_parts.append(
                    f"  - {material.get('material_name', 'Unknown')}: "
                    f"{material.get('quantity', 0)} {material.get('unit', 'units')}"
                )

        return "\n".join(summary_parts) if summary_parts else "No takeoff data available"

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=4, max=10))
    async def _call_llm(
        self,
        project_info: dict,
        takeoff_summary: str,
        pricing_rules: dict,
        markup_percentage: float,
        company_info: dict,
    ) -> dict:
        """
        Call LLM for bid generation with retry logic.

        Args:
            project_info: Project metadata
            takeoff_summary: Formatted takeoff data
            pricing_rules: Pricing information
            markup_percentage: Markup percentage
            company_info: Company information

        Returns:
            Parsed JSON response
        """
        client = self._get_client()

        # Prepare prompt
        prompt = BID_GENERATION_PROMPT.format(
            project_info=json.dumps(project_info, indent=2),
            takeoff_summary=takeoff_summary,
            material_prices=json.dumps(pricing_rules.get("material_prices", {}), indent=2),
            labor_rates=json.dumps(pricing_rules.get("labor_rates", {}), indent=2),
            markup_percentage=markup_percentage,
            company_info=json.dumps(company_info, indent=2),
            json_schema=json.dumps(self._create_json_schema(), indent=2),
        )

        try:
            logger.info("calling_llm_for_bid_generation", model=self.settings.openai_model)

            if not self.settings.openai_api_key:
                # Return mock response if no API key
                logger.warning("using_mock_bid_response")
                return self._mock_bid_response(project_info, markup_percentage)

            response = await client.chat.completions.create(
                model=self.settings.openai_model,
                messages=[
                    {"role": "system", "content": BID_GENERATION_SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                max_tokens=4096,
                temperature=0.2,
            )

            content = response.choices[0].message.content
            logger.info("llm_bid_response_received", content_length=len(content))

            # Parse JSON response
            if "```json" in content:
                parts = content.split("```json")
                if len(parts) > 1:
                    json_parts = parts[1].split("```")
                    if json_parts:
                        content = json_parts[0].strip()
            elif "```" in content:
                parts = content.split("```")
                if len(parts) > 2:
                    content = parts[1].strip()

            result = json.loads(content)
            return result

        except json.JSONDecodeError as e:
            logger.error("bid_response_json_parse_failed", error=str(e))
            return self._mock_bid_response(project_info, markup_percentage)
        except Exception as e:
            logger.error("llm_bid_call_failed", error=str(e))
            raise

    def _mock_bid_response(self, project_info: dict, markup_percentage: float) -> dict:
        """Generate mock bid response for testing."""
        material_cost = 45000.0
        labor_cost = 35000.0
        subtotal = material_cost + labor_cost
        markup_amount = subtotal * (markup_percentage / 100)
        total_price = subtotal + markup_amount

        return {
            "scope_of_work": (
                "Complete residential renovation including all materials and labor as specified "
                "in the blueprint analysis. Work includes room construction, installation of "
                "openings (doors and windows), electrical fixtures, and all materials specified."
            ),
            "line_items": [
                {
                    "description": "Framing and drywall installation",
                    "quantity": 588.0,
                    "unit": "sq ft",
                    "unit_cost": 5.50,
                    "total": 3234.0,
                },
                {
                    "description": "Interior door installation",
                    "quantity": 3,
                    "unit": "each",
                    "unit_cost": 450.0,
                    "total": 1350.0,
                },
                {
                    "description": "Window installation",
                    "quantity": 5,
                    "unit": "each",
                    "unit_cost": 850.0,
                    "total": 4250.0,
                },
                {
                    "description": "Electrical fixtures and outlets",
                    "quantity": 21,
                    "unit": "each",
                    "unit_cost": 125.0,
                    "total": 2625.0,
                },
                {
                    "description": "Flooring installation",
                    "quantity": 588.0,
                    "unit": "sq ft",
                    "unit_cost": 8.50,
                    "total": 4998.0,
                },
                {
                    "description": "Labor - General carpentry",
                    "quantity": 200,
                    "unit": "hours",
                    "unit_cost": 75.0,
                    "total": 15000.0,
                },
                {
                    "description": "Labor - Electrical work",
                    "quantity": 100,
                    "unit": "hours",
                    "unit_cost": 95.0,
                    "total": 9500.0,
                },
                {
                    "description": "Paint and finishing",
                    "quantity": 588.0,
                    "unit": "sq ft",
                    "unit_cost": 3.50,
                    "total": 2058.0,
                },
            ],
            "labor_cost": labor_cost,
            "material_cost": material_cost,
            "subtotal": subtotal,
            "markup_amount": markup_amount,
            "total_price": total_price,
            "exclusions": [
                "HVAC system installation and ductwork",
                "Plumbing rough-in and fixtures",
                "Exterior work including siding and roofing",
                "Permits and inspection fees",
                "Landscaping and site work",
            ],
            "inclusions": [
                "All materials for framing, drywall, and finishing",
                "Interior doors and windows as specified",
                "Basic electrical outlets and lighting fixtures",
                "Flooring materials and installation",
                "Paint and finishing materials",
                "General labor for carpentry and installation",
                "Cleanup and debris removal",
            ],
            "schedule": {
                "Phase 1 - Framing and Rough-in": "Weeks 1-2",
                "Phase 2 - Drywall and Insulation": "Weeks 3-4",
                "Phase 3 - Windows and Doors": "Week 5",
                "Phase 4 - Electrical and Fixtures": "Week 6",
                "Phase 5 - Flooring Installation": "Weeks 7-8",
                "Phase 6 - Paint and Finishing": "Weeks 9-10",
                "Final Inspection and Walkthrough": "Week 11",
            },
            "payment_terms": (
                "Payment schedule: 10% deposit upon contract signing, 30% at completion of "
                "Phase 2, 30% at completion of Phase 4, 30% upon final completion and "
                "inspection. Final payment due within 5 days of project completion."
            ),
            "warranty_terms": (
                "We provide a 1-year warranty on all workmanship and a 2-year warranty on "
                "materials. Manufacturer warranties apply to all fixtures and equipment. "
                "Any defects in materials or workmanship will be corrected at no charge "
                "during the warranty period."
            ),
            "closing_statement": (
                "Thank you for considering our bid for your project. We are committed to "
                "delivering quality workmanship on time and within budget. Our experienced "
                "team will ensure your complete satisfaction throughout the construction "
                "process. Please contact us with any questions or to schedule a meeting to "
                "discuss the project in detail."
            ),
        }

    async def generate_bid(
        self,
        takeoff_data: dict,
        pricing_rules: dict | None = None,
        company_info: dict | None = None,
        project_info: dict | None = None,
        markup_percentage: float = 20.0,
    ) -> BidPackage:
        """
        Generate professional bid package.

        Args:
            takeoff_data: Material takeoff from blueprint analysis
            pricing_rules: Optional pricing information
            company_info: Optional company information
            project_info: Optional project metadata
            markup_percentage: Markup percentage to apply

        Returns:
            Complete bid package

        Raises:
            Exception: If bid generation fails
        """
        try:
            logger.info("starting_bid_generation", markup=markup_percentage)

            # Prepare data
            pricing_rules = pricing_rules or {
                "material_prices": {"drywall": 1.50, "lumber": 3.00, "paint": 25.00},
                "labor_rates": {"carpentry": 75.00, "electrical": 95.00, "general": 65.00},
            }
            company_info = company_info or {
                "name": "Quality Construction Co.",
                "license": "CA-123456",
                "insurance": "Fully insured and bonded",
            }
            project_info = project_info or {"name": "Residential Renovation"}

            takeoff_summary = self._prepare_takeoff_summary(takeoff_data)

            # Call LLM
            response = await self._call_llm(
                project_info, takeoff_summary, pricing_rules, markup_percentage, company_info
            )

            # Parse into Pydantic model
            bid_package = BidPackage.model_validate(response)

            logger.info(
                "bid_generation_complete",
                bid_id=bid_package.bid_id,
                total_price=bid_package.total_price,
                line_items=len(bid_package.line_items),
            )

            return bid_package

        except Exception as e:
            logger.error("bid_generation_failed", error=str(e))
            raise Exception(f"Bid generation failed: {e}") from e
